---
- hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: install git
    package:
     name: git
     state: present
  - name: install java
    package:
     name: java-1.8.0-openjdk-devel
     state: present
  - name: install docker
    package:
     name: docker
     state: present
  - name : start docker
    service:
     name: docker
     state: started
